import Head from 'next/head'
import Homepage from './home/home'
import Footer from './header/footer'
import Navbar from './header/navbar'
import logo from './assets/logo.png'


export default function Home() {

  return (
    <div className="h-screen ">
      <Head>
        <title>WASolutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logo} />
      </Head>
    <Navbar className='fixed z-auto'/>
    <div className='scrollbar scrollbar-thumb-gray-900 scrollbar-track-gray-100' >
    <Homepage/>
    <Footer/>
    </div>
    </div>
  )
}
