import Head from 'next/head'
import Section1 from './body/sec1'
import Section2 from './body/sec2'
import Section3 from './body/sec3'
import Section4 from './body/sec4'
import Section5 from './body/sec5'
import Section6 from './body/sec6'
import Section7 from './body/sec7'
import Footer from './header/footer'
import Navbar from './header/navbar'
import logo from './assets/logo.png'


export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>WASolutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logo} />
      </Head>
        
    <Navbar className='fixed'/>
    <Section1/>
    <Section2/>
    <Section3/>
    <Section4/>
    <Section5/>
    <Section6/>
    <Section7/>
    <Footer/>
    </div>
  )
}
