import Head from 'next/head'
import Homepage from './home/home'
import {Logo} from './assets/logo.png'


export default function Home() {

  return (
    <div className="h-screen ">
      <Head>
        <title>WASolutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={Logo} />
      </Head>
    <Homepage/>
    </div>
  )
}
